### ISSUE TITLE
installation: Parameter 'path' not declared

### ISSUE THREAD

**Issue by bharding512** [space-physics/NCAR-GLOW#1]
First off, thanks to Michael and Stan for open sourcing this project. It's a huge help.

I have an issue installing this on Centos 7 / Python 3.7. The error is copied below. Two possible clues:
- I can install and run standalone GLOW just fine (using instructions on https://github.com/NCAR/GLOW)
- If I replace iri90.f with the one in standalone GLOW (https://github.com/NCAR/GLOW/blob/master/iri90.f) then I can install this package (i.e., NCAR-GLOW) just fine. But I'm worried I broke something by doing that.

```
gyarados-NCAR-GLOW [149] cmake --build build -j
Scanning dependencies of target cglow
[ 15%] Building Fortran object CMakeFiles/cglow.dir/solzen.f90.o
[ 19%] Building Fortran object CMakeFiles/cglow.dir/cglow.f90.o
[ 19%] Building Fortran object CMakeFiles/cglow.dir/rcolum.f90.o
[ 19%] Building Fortran object CMakeFiles/cglow.dir/fieldm.f.o
[ 38%] Building Fortran object CMakeFiles/cglow.dir/iri90.f.o
[ 38%] Building Fortran object CMakeFiles/cglow.dir/maxt.f90.o
[ 38%] Building Fortran object CMakeFiles/cglow.dir/qback.f90.o
[ 46%] Building Fortran object CMakeFiles/cglow.dir/egrid.f90.o
[ 50%] Building Fortran object CMakeFiles/cglow.dir/snoemint.f90.o
[ 50%] Building Fortran object CMakeFiles/cglow.dir/conduct.f90.o
[ 50%] Building Fortran object CMakeFiles/cglow.dir/geomag.f90.o
[ 50%] Building Fortran object CMakeFiles/cglow.dir/nrlmsise00.f.o
[ 50%] Building Fortran object CMakeFiles/cglow.dir/mzgrid.f90.o
/home/bharding/src/NCAR-GLOW/src/iri90.f:442.16:
8448  error stop path // ' IRI90: File not found'                       
                1
Error: Parameter 'path' at (1) has not been declared or is a variable, which does not reduce to a constant expression
/home/bharding/src/NCAR-GLOW/src/iri90.f:162.23:
       SUBROUTINE IRI90(JF,JMAG,ALATI,ALONG,RZ12,MMDD,DHOUR,            
                       1
Error: Label 8448 referenced at (1) is never defined
/home/bharding/src/NCAR-GLOW/src/iri90.f:162.23:
       SUBROUTINE IRI90(JF,JMAG,ALATI,ALONG,RZ12,MMDD,DHOUR,            
                       1
Error: Label 8448 referenced at (1) is never defined
gmake[2]: *** [CMakeFiles/cglow.dir/iri90.f.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/cglow.dir/all] Error 2
gmake: *** [all] Error 2

```

**Comment by scivision** [comment]
I made a number of cleanups, including that old Fortran compilers can be used. Just do a
```sh
git pull
```
and try again.

Thanks!

**Comment by bharding512** [comment]
Thanks! I had to:

```
pip install --upgrade setuptools
pip install pytest
```

I had setuptools-39.0.1 but I think geomagindices requires 40.0. I'm not sure why I had to do that manually, but once I did, installing ncar-glow was a breeze, and "python -m pytest" was a success.

In any case, it's working great now. Thanks again!

**Comment by scivision** [comment]
Thanks I fixed the setuptools auto-upgrade as well. 
I made a number of further improvements this afternoon, packing all the outputs into a single [xarray.Dataset](http://xarray.pydata.org/en/stable/generated/xarray.Dataset.html).

I have been overhauling all my packages like this to work better for auto-compiling without manual intervention, so let me know of any other wrinkles. THanks

**Comment by scivision** [comment]
Stan provides the underlying science and model, I provide the easy interface.
Let me know if you'd like something. It's usually easy to add more output data.

**Comment by bharding512** [comment]
The new improvements you just made installed great as well, and things seem to be working as expected. As an added bonus, I tried to recreate Figure 3c in Solomon [2017] and it compares well, which gives me a lot of confidence. Thanks!

Figure 3c of Solomon [2017]:
![image](https://user-images.githubusercontent.com/8883135/54724603-0ddf6f80-4b29-11e9-9e56-052b9dee5759.png)

From this package:
![image](https://user-images.githubusercontent.com/8883135/54724597-04560780-4b29-11e9-91eb-30105b6c331e.png)
