### ISSUE TITLE
Installing on Mac M2 / Sonoma

### ISSUE THREAD

**Issue by bharding512** [space-physics/NCAR-GLOW#6]
Has anyone gotten this (or the version by @sunipkm) to install on a recent Macbook? I can't seem to make this work on my new Macbook Air M2 / Sonoma 14.0.

Some sources talk about f2py issues with Xcode command line tools 15 (https://github.com/orgs/Homebrew/discussions/4794), but I can't revert to 14 on this OS. Installing gfortran through conda gives me an error that looks like a 14 vs 15 error. For @sunipkm's version of GLOW, I get "`numpy.distutils` is deprecated since NumPy 1.23.0".

For this (space-physics) version, installing works fine, but then on the first import (which is when the code actually gets compiled) I get a bunch of cmake errors, or meson errors after I tried installing meson (e.g., ERROR: Unknown linker(s): [['arm64-apple-darwin20.0.0-ar']])

This stuff really isn't my expertise, so if anyone has any tips, please let me know. I've been cracking away at this for a couple days to no end. Thanks.

**Comment by sunipkm** [comment]
@bharding512 I think I know what you are running into. The version I have working right now is compatible with numpy 1.15 or greater AFAIK. I have a MBP M1 Pro running Sonoma 14.3.1, numpy 1.21.5 and it installs no problem (use the development branch). You need to install gfortran through homebrew and it should work fine. If you want to get a debug log, you can clone mine and install with `pip install . --config-settings=builddir=build &> build.log`, that way you can see what's going wrong in the build process in `build.log`. There is a `dylib` version mismatch that I remember between Anaconda and homebrew gfortran, I simply create a backup of the Anaconda version and create a symlink of the homebrew `dylib` with the same name in the place where Anaconda/numpy expects it. Let me know how it goes.

**Comment by bharding512** [comment]
Thanks for the quick response. I've attached here the build log, where I used Python 3.9.18 and numpy 1.21.5
[conda_build.log](https://github.com/space-physics/NCAR-GLOW/files/14577673/conda_build.log)

Since you mentioned issues with Anaconda, I also tried using a separate Python installation from pyevn, but that also fails -- with different errors:
[pyenv_build.log](https://github.com/space-physics/NCAR-GLOW/files/14577672/pyenv_build.log)

I don't have any experience with dylib, so if you're able to provide any more pointers about what you mean about that, I'd appreciate it.

**Comment by sunipkm** [comment]
@bharding512 for the second env: Switch to the `development` branch and `pip install .`, that should fix it. I just developed that fix a couple days ago and it has not been merged to the `master` branch. It should work out for the first env too, looks like you are just trying to install an older version (if you `pip install glowpython`, it's gonna pull a much older version from PyPi. I have not yet updated glowpython to the latest there).

**Comment by bharding512** [comment]
That worked! (with pyenv but not with conda). I think this solves it for me, so I'll close the issue. Thanks so much for your quick help. For anyone else here is what I did (inside a pyenv-created environment)
```
$ git clone -b development https://github.com/sunipkm/glowpython.git
$ cd glowpython
$ pip install .
```

P.S. I have been making some minor changes to your code here: https://github.com/bharding512/NCAR-GLOW Let me know if you're ever open to pull requests and I'll see if I can merge my changes.

**Comment by sunipkm** [comment]
@bharding512 I would be happy to incorporate changes. Contributions are welcome!
